# Generated by Django 5.2.4 on 2025-07-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memberships',
            table='memberships',
        ),
    ]
