# Generated by Django 5.2.4 on 2025-07-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_memberships_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.students')),
            ],
            options={
                'db_table': 'club_application',
            },
        ),
    ]
