# Generated by Django 5.2.4 on 2025-07-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_clubapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_form', models.ImageField(upload_to='membership_applications/medical_forms/')),
                ('certificate_of_recognition', models.ImageField(upload_to='membership_applications/cor/')),
                ('student_id_card', models.ImageField(upload_to='membership_applications/identification_cards')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.students')),
            ],
        ),
    ]
