# Generated by Django 5.2.4 on 2025-08-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_memberapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberapplication',
            name='student_id_card',
            field=models.ImageField(upload_to='membership_applications/identification_cards/'),
        ),
    ]
