# Generated by Django 5.2.4 on 2025-08-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_alter_memberapplication_student_id_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubapplication',
            options={'ordering': ['-date_submitted'], 'verbose_name_plural': 'Club Applications'},
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description about this club', null=True),
        ),
    ]
