# Generated by Django 5.2.4 on 2025-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_alter_clubapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='club_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
