# Generated by Django 5.2.4 on 2025-08-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_alter_clubapplication_club_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberapplication',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelTable(
            name='memberapplication',
            table='member_application',
        ),
    ]
