# Generated by Django 5.2 on 2025-08-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0008_alter_memberapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='club',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='club',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='student',
        ),
        migrations.RemoveField(
            model_name='memberships',
            name='student',
        ),
        migrations.DeleteModel(
            name='ClubApplication',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.DeleteModel(
            name='MemberApplication',
        ),
        migrations.DeleteModel(
            name='Memberships',
        ),
    ]
