# Generated by Django 5.2.4 on 2025-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0009_remove_memberapplication_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('role', models.IntegerField(choices=[(0, 'Student'), (1, 'Instructor'), (2, 'Coordinator'), (3, 'Admin')], default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
