# Generated by Django 5.2.4 on 2025-08-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_clubapplication_submitted_by_and_more'),
        ('landing_page', '0010_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
