# Generated by Django 5.2 on 2025-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0011_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (2, 'Officer'), (3, 'Instructor'), (4, 'Coordinator'), (5, 'Admin')], default=0),
        ),
    ]
