# Generated by Django 5.2 on 2025-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0012_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (1, 'Officer'), (2, 'Instructor'), (3, 'Coordinator'), (4, 'Admin')], default=0),
        ),
    ]
