# Generated by Django 5.2 on 2025-09-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetrequest',
            name='details',
        ),
    ]
