# Generated by Django 5.2 on 2025-09-04 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
