# Generated by Django 5.2 on 2025-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_club', '0002_budgetrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
