# Generated by Django 5.2 on 2025-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_club', '0003_alter_budgetrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='title',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
