# Generated by Django 5.2.4 on 2025-12-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_clubapplication_rejection_reason'),
        ('individual_club', '0004_budgetrequest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('platform', models.IntegerField(choices=[(0, 'Facebook'), (1, 'Twitter/X'), (2, 'Instagram')], default=0)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
            ],
        ),
    ]
