# Generated by Django 5.2.4 on 2025-12-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_clubapplication_rejection_reason'),
        ('individual_club', '0005_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.AlterModelTable(
            name='link',
            table='link',
        ),
    ]
