# Generated by Django 5.2.4 on 2025-12-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual_club', '0006_rename_links_link_alter_link_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='club_id',
            new_name='club',
        ),
    ]
