# Generated by Django 5.2 on 2025-08-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0009_remove_memberapplication_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255, unique=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description about this club', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.students')),
            ],
            options={
                'verbose_name_plural': 'Club Applications',
                'db_table': 'club_application',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_form', models.ImageField(upload_to='membership_applications/medical_forms/')),
                ('certificate_of_recognition', models.ImageField(upload_to='membership_applications/cor/')),
                ('student_id_card', models.ImageField(upload_to='membership_applications/identification_cards/')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.students')),
            ],
            options={
                'db_table': 'member_application',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_officer', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.students')),
            ],
            options={
                'db_table': 'memberships',
                'constraints': [models.UniqueConstraint(fields=('student', 'club'), name='unique_membership')],
            },
        ),
    ]
