# Generated by Django 5.2 on 2025-09-03 14:17

import clubs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'school_branch',
            },
        ),
        migrations.CreateModel(
            name='ClubApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Club Application/Banners/')),
                ('constitutions_and_by_laws', models.FileField(upload_to='Club Application/Constitutions and By Laws/')),
                ('acceptance_letter', models.FileField(upload_to='Club Application/Acceptance Letter/')),
                ('list_of_officer', models.FileField(upload_to='Club Application/List of Officer/')),
                ('calendar_of_activities', models.FileField(upload_to='Club Application/Calendar of Activities/')),
                ('action_plan', models.FileField(upload_to='Club Application/Action Plan/')),
                ('year_level', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description about this club', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_adviser', to='landing_page.users')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_application', to='landing_page.users')),
            ],
            options={
                'verbose_name_plural': 'Club Applications',
                'db_table': 'club_application',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('year_level', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='club_applications/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advised_clubs', to='landing_page.users')),
                ('chairperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaired_clubs', to='landing_page.users')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubs.branch')),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField(choices=[(0, 'General Announcement'), (1, 'Upcoming Event'), (2, 'Important Notice'), (3, 'System Maintenance'), (4, 'Policy Update'), (5, 'Club Meeting')], default=0, verbose_name='Categories')),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-announcement_date'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_form', models.ImageField(upload_to='membership_applications/medical_forms/')),
                ('certificate_of_recognition', models.ImageField(upload_to='membership_applications/cor/')),
                ('student_id_card', models.ImageField(upload_to='membership_applications/identification_cards/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='membership_applications/signatures/')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.users')),
            ],
            options={
                'db_table': 'member_application',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='Memberships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_officer', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.users')),
            ],
            options={
                'db_table': 'memberships',
                'constraints': [models.UniqueConstraint(fields=('student', 'club'), name='unique_membership')],
            },
        ),
    ]
