# Generated by Django 5.2 on 2025-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
