# Generated by Django 5.2.4 on 2025-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='location',
            field=models.IntegerField(choices=[(0, 'Main'), (1, "Millionaire's Village"), (2, 'Bulacan')], default=0, verbose_name='Location'),
        ),
        migrations.AlterModelTable(
            name='clubs',
            table='clubs',
        ),
    ]
