# Generated by Django 5.2.4 on 2025-09-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_announcement_test_field'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='announcement',
        ),
    ]
