# Generated by Django 5.2 on 2025-08-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubapplication_location_alter_clubs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='campus',
            field=models.CharField(default='No campus specified', max_length=100),
        ),
    ]
