# Generated by Django 5.2.4 on 2025-08-07 13:27

import clubs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubs_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'school_branch',
            },
        ),
        migrations.RemoveField(
            model_name='clubs',
            name='campus',
        ),
        migrations.AddField(
            model_name='clubs',
            name='location',
            field=models.ForeignKey(default=clubs.models.get_default_branch, on_delete=django.db.models.deletion.CASCADE, to='clubs.branch'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.branch'),
        ),
    ]
