# Generated by Django 5.2.4 on 2025-09-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_announcement_table'),
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubapplication',
            options={'ordering': ['-date_submitted'], 'verbose_name': 'Club Application', 'verbose_name_plural': 'Club Applications'},
        ),
        migrations.RemoveField(
            model_name='clubapplication',
            name='list_of_officer',
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='list_of_officers',
            field=models.FileField(default='', upload_to='Club Application/List of Officers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to='landing_page.users'),
        ),
    ]
