# Generated by Django 5.2.4 on 2025-09-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_clubapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='test_field',
        ),
    ]
