# Generated by Django 5.2.4 on 2025-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_branch_remove_clubs_campus_clubs_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='banner',
            field=models.ImageField(null=True, upload_to='club_applications/banners/'),
        ),
    ]
