# Generated by Django 5.2.4 on 2025-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubapplication_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
