# Generated by Django 5.2.4 on 2025-08-11 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubs_description'),
        ('landing_page', '0010_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.users'),
        ),
    ]
