# Generated by Django 5.2.4 on 2025-09-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubapplication_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='year_level',
            field=models.IntegerField(choices=[(0, 'First Year'), (1, 'Second Year'), (2, 'Third Year'), (3, 'Fourth Year')], verbose_name='Year Level'),
        ),
    ]
