# Generated by Django 5.2.4 on 2025-08-24 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_clubapplication_submitted_by_and_more'),
        ('landing_page', '0013_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='acronym',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='adviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_adviser', to='landing_page.users'),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubapplication',
            name='year_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='acronym',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advised_clubs', to='landing_page.users'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='club_applications/banners/'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='chairperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaired_clubs', to='landing_page.users'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clubs',
            name='year_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='club_applications/banners/'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_application', to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='club_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
