# Generated by Django 5.2.4 on 2025-09-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_clubapplication_year_level'),
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='acronym',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_adviser', to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='description',
            field=models.TextField(help_text='Enter a description about this club'),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to='landing_page.users'),
        ),
    ]
