# Generated by Django 5.2.4 on 2025-09-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_alter_clubapplication_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
