# Generated by Django 5.2.4 on 2025-08-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_clubapplication_acronym_clubapplication_adviser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='acronym',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
