# Generated by Django 5.2.4 on 2025-08-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubs_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplication',
            name='acronym',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
