# Generated by Django 5.2.4 on 2025-09-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_alter_clubapplication_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
