# Generated by Django 5.2.4 on 2025-09-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.course'),
            preserve_default=False,
        ),
    ]
