# Generated by Django 5.2.4 on 2025-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubapplication_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='year_level',
            field=models.IntegerField(choices=[(0, 'First Year'), (1, 'Second Year'), (2, 'Third Year'), (3, 'Fourth Year')], default=0, verbose_name='Year Level'),
            preserve_default=False,
        ),
    ]
