# Generated by Django 5.2.4 on 2025-08-31 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_budgetrequest_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='budgetrequest',
            table='budget_request',
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
    ]
