# Generated by Django 5.2.4 on 2025-09-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_clubs_year_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='location',
        ),
    ]
