# Generated by Django 5.2.4 on 2025-09-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_budgetrequest_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberapplication',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='membership_applications/signatures/'),
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, verbose_name='Status'),
        ),
    ]
