# Generated by Django 5.2.4 on 2025-09-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_remove_clubs_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('course_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.AlterField(
            model_name='clubapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.program'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
