# Generated by Django 5.2.4 on 2025-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_program_alter_clubapplication_program_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='program',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
    ]
