# Generated by Django 5.2.4 on 2025-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_program_id_alter_program_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.AlterField(
            model_name='program',
            name='course_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
