# Generated by Django 5.2.4 on 2025-09-06 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_remove_program_id_alter_program_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='program',
            field=models.ForeignKey(default='BSIT', on_delete=django.db.models.deletion.CASCADE, to='clubs.program'),
            preserve_default=False,
        ),
    ]
