# Generated by Django 5.2.4 on 2025-09-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_clubs_program'),
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='acronym',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advised_clubs', to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaired_clubs', to='landing_page.users'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='description',
            field=models.TextField(help_text='Enter a description about this club'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
