# Generated by Django 5.2.4 on 2025-09-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_clubs_acronym_alter_clubs_adviser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubapplication',
            old_name='program',
            new_name='program_fk',
        ),
    ]
