# Generated by Django 5.2.4 on 2025-09-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_rename_program_clubapplication_program_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubapplication',
            old_name='program_fk',
            new_name='program',
        ),
    ]
