# Generated by Django 5.2.4 on 2025-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_rename_program_fk_clubapplication_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='medical_form',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='memberapplication',
            name='student_id_card',
        ),
        migrations.AddField(
            model_name='memberapplication',
            name='response_text',
            field=models.TextField(blank=True, help_text='Optional: Anything you would like to know about the club?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberapplication',
            name='certificate_of_recognition',
            field=models.FileField(upload_to='membership_applications/cor/'),
        ),
    ]
