# Generated by Django 5.2.4 on 2025-09-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_remove_memberapplication_medical_form_and_more'),
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberapplication',
            unique_together={('student', 'club')},
        ),
    ]
