# Generated by Django 5.2.4 on 2025-09-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_alter_memberapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberships',
            name='application_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clubs.memberapplication'),
            preserve_default=False,
        ),
    ]
