# Generated by Django 5.2.4 on 2025-09-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_memberships_application_id'),
        ('landing_page', '__first__'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberapplication',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='memberapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 0)), fields=('student', 'club'), name='unique_pending_applications'),
        ),
    ]
