# Generated by Django 5.2.4 on 2025-09-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_alter_memberapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
