# Generated by Django 5.2.4 on 2025-09-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_delete_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='is_officer',
        ),
        migrations.AddField(
            model_name='memberships',
            name='role',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Representative'), (2, 'Public Relation Officer'), (3, 'Auditor'), (4, 'Treasurer'), (5, 'Secretary'), (6, 'Chairperson')], default=0, verbose_name='Role'),
        ),
    ]
