# Generated by Django 5.2.4 on 2025-09-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_remove_memberships_is_officer_memberships_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='application_id',
        ),
    ]
