# Generated by Django 5.2 on 2025-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_remove_memberships_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(),
        ),
    ]
