# Generated by Django 5.2 on 2025-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_announcement_image_alter_announcement_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.IntegerField(choices=[(0, 'General Announcement'), (1, 'Upcoming Event'), (2, 'Important Notice'), (3, 'System Maintenance'), (4, 'Policy Update'), (5, 'Club Meeting')], default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
