# Generated by Django 5.2.4 on 2025-10-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_alter_announcement_category_alter_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubapplication',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
