# Generated by Django 5.2.4 on 2026-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_clubapplication_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberships',
            name='role',
        ),
        migrations.AddField(
            model_name='memberships',
            name='is_officer',
            field=models.BooleanField(default=False),
        ),
    ]
